/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AscendRouteImport } from './routes/ascend'
import { Route as ArcaRouteImport } from './routes/arca'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalVisitsRouteImport } from './routes/portal.visits'
import { Route as PortalProgressRouteImport } from './routes/portal.progress'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalMedsRouteImport } from './routes/portal.meds'
import { Route as PortalLabsRouteImport } from './routes/portal.labs'
import { Route as PortalBillingRouteImport } from './routes/portal.billing'
import { Route as PortalAccountRouteImport } from './routes/portal.account'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as CompareCompetitorRouteImport } from './routes/compare/$competitor'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminWebsiteRouteImport } from './routes/admin/website'
import { Route as AdminTelehealthRouteImport } from './routes/admin/telehealth'
import { Route as AdminSocialRouteImport } from './routes/admin/social'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminScribeRouteImport } from './routes/admin/scribe'
import { Route as AdminResultsGalleryRouteImport } from './routes/admin/results-gallery'
import { Route as AdminReputationRouteImport } from './routes/admin/reputation'
import { Route as AdminReferralsRouteImport } from './routes/admin/referrals'
import { Route as AdminRcmRouteImport } from './routes/admin/rcm'
import { Route as AdminProtocolsRouteImport } from './routes/admin/protocols'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminProductRevenueRouteImport } from './routes/admin/product-revenue'
import { Route as AdminPosRouteImport } from './routes/admin/pos'
import { Route as AdminPopulationRouteImport } from './routes/admin/population'
import { Route as AdminPhotoReviewsRouteImport } from './routes/admin/photo-reviews'
import { Route as AdminPhoneCallsRouteImport } from './routes/admin/phone-calls'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminPaidChannelsRouteImport } from './routes/admin/paid-channels'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminMembershipsRouteImport } from './routes/admin/memberships'
import { Route as AdminMembershipHealthRouteImport } from './routes/admin/membership-health'
import { Route as AdminLocationsRouteImport } from './routes/admin/locations'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminIntakeRouteImport } from './routes/admin/intake'
import { Route as AdminHipaaRouteImport } from './routes/admin/hipaa'
import { Route as AdminFitRouteImport } from './routes/admin/fit'
import { Route as AdminEmailSmsRouteImport } from './routes/admin/email-sms'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCoachPerformanceRouteImport } from './routes/admin/coach-performance'
import { Route as AdminChartsRouteImport } from './routes/admin/charts'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsAnalyticsRouteImport } from './routes/admin/bookings-analytics'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAcquisitionRouteImport } from './routes/admin/acquisition'
import { Route as PortalShopIndexRouteImport } from './routes/portal.shop.index'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin/patients.index'
import { Route as AdminFitIndexRouteImport } from './routes/admin/fit.index'
import { Route as PortalVisitIdRouteImport } from './routes/portal.visit.$id'
import { Route as PortalShopOrdersRouteImport } from './routes/portal.shop.orders'
import { Route as PortalShopCartRouteImport } from './routes/portal.shop.cart'
import { Route as PortalShopProductIdRouteImport } from './routes/portal.shop.$productId'
import { Route as AdminPatientsIdRouteImport } from './routes/admin/patients.$id'
import { Route as AdminFitWorkoutsRouteImport } from './routes/admin/fit.workouts'
import { Route as AdminFitVideosRouteImport } from './routes/admin/fit.videos'
import { Route as AdminFitScansRouteImport } from './routes/admin/fit.scans'
import { Route as AdminFitReviewsRouteImport } from './routes/admin/fit.reviews'
import { Route as AdminFitPortalRouteImport } from './routes/admin/fit.portal'
import { Route as AdminFitNutritionRouteImport } from './routes/admin/fit.nutrition'
import { Route as AdminFitMessagesRouteImport } from './routes/admin/fit.messages'
import { Route as AdminFitLiveRouteImport } from './routes/admin/fit.live'
import { Route as AdminFitLeadsRouteImport } from './routes/admin/fit.leads'
import { Route as AdminFitClientsRouteImport } from './routes/admin/fit.clients'
import { Route as AdminFitChallengesRouteImport } from './routes/admin/fit.challenges'
import { Route as AdminFitCalendarRouteImport } from './routes/admin/fit.calendar'
import { Route as AdminFitBusinessRouteImport } from './routes/admin/fit.business'
import { Route as AdminFitBillingRouteImport } from './routes/admin/fit.billing'
import { Route as AdminFitClientsIndexRouteImport } from './routes/admin/fit.clients.index'
import { Route as AdminFitWorkoutsBuilderRouteImport } from './routes/admin/fit.workouts.builder'
import { Route as AdminFitClientsIdRouteImport } from './routes/admin/fit.clients.$id'

const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendRoute = AscendRouteImport.update({
  id: '/ascend',
  path: '/ascend',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcaRoute = ArcaRouteImport.update({
  id: '/arca',
  path: '/arca',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalVisitsRoute = PortalVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProgressRoute = PortalProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMedsRoute = PortalMedsRouteImport.update({
  id: '/meds',
  path: '/meds',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLabsRoute = PortalLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FeaturesRoute,
} as any)
const CompareCompetitorRoute = CompareCompetitorRouteImport.update({
  id: '/compare/$competitor',
  path: '/compare/$competitor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTelehealthRoute = AdminTelehealthRouteImport.update({
  id: '/telehealth',
  path: '/telehealth',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSocialRoute = AdminSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScribeRoute = AdminScribeRouteImport.update({
  id: '/scribe',
  path: '/scribe',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResultsGalleryRoute = AdminResultsGalleryRouteImport.update({
  id: '/results-gallery',
  path: '/results-gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReputationRoute = AdminReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRcmRoute = AdminRcmRouteImport.update({
  id: '/rcm',
  path: '/rcm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProtocolsRoute = AdminProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductRevenueRoute = AdminProductRevenueRouteImport.update({
  id: '/product-revenue',
  path: '/product-revenue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPopulationRoute = AdminPopulationRouteImport.update({
  id: '/population',
  path: '/population',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPhotoReviewsRoute = AdminPhotoReviewsRouteImport.update({
  id: '/photo-reviews',
  path: '/photo-reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPhoneCallsRoute = AdminPhoneCallsRouteImport.update({
  id: '/phone-calls',
  path: '/phone-calls',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaidChannelsRoute = AdminPaidChannelsRouteImport.update({
  id: '/paid-channels',
  path: '/paid-channels',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembershipHealthRoute = AdminMembershipHealthRouteImport.update({
  id: '/membership-health',
  path: '/membership-health',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntakeRoute = AdminIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHipaaRoute = AdminHipaaRouteImport.update({
  id: '/hipaa',
  path: '/hipaa',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFitRoute = AdminFitRouteImport.update({
  id: '/fit',
  path: '/fit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailSmsRoute = AdminEmailSmsRouteImport.update({
  id: '/email-sms',
  path: '/email-sms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoachPerformanceRoute = AdminCoachPerformanceRouteImport.update({
  id: '/coach-performance',
  path: '/coach-performance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChartsRoute = AdminChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsAnalyticsRoute = AdminBookingsAnalyticsRouteImport.update({
  id: '/bookings-analytics',
  path: '/bookings-analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAcquisitionRoute = AdminAcquisitionRouteImport.update({
  id: '/acquisition',
  path: '/acquisition',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalShopIndexRoute = PortalShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminFitIndexRoute = AdminFitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFitRoute,
} as any)
const PortalVisitIdRoute = PortalVisitIdRouteImport.update({
  id: '/visit/$id',
  path: '/visit/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalShopOrdersRoute = PortalShopOrdersRouteImport.update({
  id: '/shop/orders',
  path: '/shop/orders',
  getParentRoute: () => PortalRoute,
} as any)
const PortalShopCartRoute = PortalShopCartRouteImport.update({
  id: '/shop/cart',
  path: '/shop/cart',
  getParentRoute: () => PortalRoute,
} as any)
const PortalShopProductIdRoute = PortalShopProductIdRouteImport.update({
  id: '/shop/$productId',
  path: '/shop/$productId',
  getParentRoute: () => PortalRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminFitWorkoutsRoute = AdminFitWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitVideosRoute = AdminFitVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitScansRoute = AdminFitScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitReviewsRoute = AdminFitReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitPortalRoute = AdminFitPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitNutritionRoute = AdminFitNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitMessagesRoute = AdminFitMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitLiveRoute = AdminFitLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitLeadsRoute = AdminFitLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitClientsRoute = AdminFitClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitChallengesRoute = AdminFitChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitCalendarRoute = AdminFitCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitBusinessRoute = AdminFitBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitBillingRoute = AdminFitBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminFitRoute,
} as any)
const AdminFitClientsIndexRoute = AdminFitClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFitClientsRoute,
} as any)
const AdminFitWorkoutsBuilderRoute = AdminFitWorkoutsBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AdminFitWorkoutsRoute,
} as any)
const AdminFitClientsIdRoute = AdminFitClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFitClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/arca': typeof ArcaRoute
  '/ascend': typeof AscendRoute
  '/blog': typeof BlogRouteWithChildren
  '/customers': typeof CustomersRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/admin/acquisition': typeof AdminAcquisitionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/bookings-analytics': typeof AdminBookingsAnalyticsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/coach-performance': typeof AdminCoachPerformanceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email-sms': typeof AdminEmailSmsRoute
  '/admin/fit': typeof AdminFitRouteWithChildren
  '/admin/hipaa': typeof AdminHipaaRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/membership-health': typeof AdminMembershipHealthRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/paid-channels': typeof AdminPaidChannelsRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/phone-calls': typeof AdminPhoneCallsRoute
  '/admin/photo-reviews': typeof AdminPhotoReviewsRoute
  '/admin/population': typeof AdminPopulationRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/product-revenue': typeof AdminProductRevenueRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/protocols': typeof AdminProtocolsRoute
  '/admin/rcm': typeof AdminRcmRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reputation': typeof AdminReputationRoute
  '/admin/results-gallery': typeof AdminResultsGalleryRoute
  '/admin/scribe': typeof AdminScribeRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/telehealth': typeof AdminTelehealthRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$competitor': typeof CompareCompetitorRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/meds': typeof PortalMedsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/visits': typeof PortalVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/fit/billing': typeof AdminFitBillingRoute
  '/admin/fit/business': typeof AdminFitBusinessRoute
  '/admin/fit/calendar': typeof AdminFitCalendarRoute
  '/admin/fit/challenges': typeof AdminFitChallengesRoute
  '/admin/fit/clients': typeof AdminFitClientsRouteWithChildren
  '/admin/fit/leads': typeof AdminFitLeadsRoute
  '/admin/fit/live': typeof AdminFitLiveRoute
  '/admin/fit/messages': typeof AdminFitMessagesRoute
  '/admin/fit/nutrition': typeof AdminFitNutritionRoute
  '/admin/fit/portal': typeof AdminFitPortalRoute
  '/admin/fit/reviews': typeof AdminFitReviewsRoute
  '/admin/fit/scans': typeof AdminFitScansRoute
  '/admin/fit/videos': typeof AdminFitVideosRoute
  '/admin/fit/workouts': typeof AdminFitWorkoutsRouteWithChildren
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/portal/shop/$productId': typeof PortalShopProductIdRoute
  '/portal/shop/cart': typeof PortalShopCartRoute
  '/portal/shop/orders': typeof PortalShopOrdersRoute
  '/portal/visit/$id': typeof PortalVisitIdRoute
  '/admin/fit/': typeof AdminFitIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/portal/shop/': typeof PortalShopIndexRoute
  '/admin/fit/clients/$id': typeof AdminFitClientsIdRoute
  '/admin/fit/workouts/builder': typeof AdminFitWorkoutsBuilderRoute
  '/admin/fit/clients/': typeof AdminFitClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arca': typeof ArcaRoute
  '/ascend': typeof AscendRoute
  '/blog': typeof BlogRouteWithChildren
  '/customers': typeof CustomersRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/admin/acquisition': typeof AdminAcquisitionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/bookings-analytics': typeof AdminBookingsAnalyticsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/coach-performance': typeof AdminCoachPerformanceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email-sms': typeof AdminEmailSmsRoute
  '/admin/hipaa': typeof AdminHipaaRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/membership-health': typeof AdminMembershipHealthRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/paid-channels': typeof AdminPaidChannelsRoute
  '/admin/phone-calls': typeof AdminPhoneCallsRoute
  '/admin/photo-reviews': typeof AdminPhotoReviewsRoute
  '/admin/population': typeof AdminPopulationRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/product-revenue': typeof AdminProductRevenueRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/protocols': typeof AdminProtocolsRoute
  '/admin/rcm': typeof AdminRcmRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reputation': typeof AdminReputationRoute
  '/admin/results-gallery': typeof AdminResultsGalleryRoute
  '/admin/scribe': typeof AdminScribeRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/telehealth': typeof AdminTelehealthRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$competitor': typeof CompareCompetitorRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/meds': typeof PortalMedsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/visits': typeof PortalVisitsRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/fit/billing': typeof AdminFitBillingRoute
  '/admin/fit/business': typeof AdminFitBusinessRoute
  '/admin/fit/calendar': typeof AdminFitCalendarRoute
  '/admin/fit/challenges': typeof AdminFitChallengesRoute
  '/admin/fit/leads': typeof AdminFitLeadsRoute
  '/admin/fit/live': typeof AdminFitLiveRoute
  '/admin/fit/messages': typeof AdminFitMessagesRoute
  '/admin/fit/nutrition': typeof AdminFitNutritionRoute
  '/admin/fit/portal': typeof AdminFitPortalRoute
  '/admin/fit/reviews': typeof AdminFitReviewsRoute
  '/admin/fit/scans': typeof AdminFitScansRoute
  '/admin/fit/videos': typeof AdminFitVideosRoute
  '/admin/fit/workouts': typeof AdminFitWorkoutsRouteWithChildren
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/portal/shop/$productId': typeof PortalShopProductIdRoute
  '/portal/shop/cart': typeof PortalShopCartRoute
  '/portal/shop/orders': typeof PortalShopOrdersRoute
  '/portal/visit/$id': typeof PortalVisitIdRoute
  '/admin/fit': typeof AdminFitIndexRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/portal/shop': typeof PortalShopIndexRoute
  '/admin/fit/clients/$id': typeof AdminFitClientsIdRoute
  '/admin/fit/workouts/builder': typeof AdminFitWorkoutsBuilderRoute
  '/admin/fit/clients': typeof AdminFitClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/arca': typeof ArcaRoute
  '/ascend': typeof AscendRoute
  '/blog': typeof BlogRouteWithChildren
  '/customers': typeof CustomersRoute
  '/demo': typeof DemoRoute
  '/features': typeof FeaturesRouteWithChildren
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/security': typeof SecurityRoute
  '/admin/acquisition': typeof AdminAcquisitionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/bookings-analytics': typeof AdminBookingsAnalyticsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/charts': typeof AdminChartsRoute
  '/admin/coach-performance': typeof AdminCoachPerformanceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email-sms': typeof AdminEmailSmsRoute
  '/admin/fit': typeof AdminFitRouteWithChildren
  '/admin/hipaa': typeof AdminHipaaRoute
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/membership-health': typeof AdminMembershipHealthRoute
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/paid-channels': typeof AdminPaidChannelsRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/phone-calls': typeof AdminPhoneCallsRoute
  '/admin/photo-reviews': typeof AdminPhotoReviewsRoute
  '/admin/population': typeof AdminPopulationRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/product-revenue': typeof AdminProductRevenueRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/protocols': typeof AdminProtocolsRoute
  '/admin/rcm': typeof AdminRcmRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/reputation': typeof AdminReputationRoute
  '/admin/results-gallery': typeof AdminResultsGalleryRoute
  '/admin/scribe': typeof AdminScribeRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/social': typeof AdminSocialRoute
  '/admin/telehealth': typeof AdminTelehealthRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$competitor': typeof CompareCompetitorRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/meds': typeof PortalMedsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/visits': typeof PortalVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/fit/billing': typeof AdminFitBillingRoute
  '/admin/fit/business': typeof AdminFitBusinessRoute
  '/admin/fit/calendar': typeof AdminFitCalendarRoute
  '/admin/fit/challenges': typeof AdminFitChallengesRoute
  '/admin/fit/clients': typeof AdminFitClientsRouteWithChildren
  '/admin/fit/leads': typeof AdminFitLeadsRoute
  '/admin/fit/live': typeof AdminFitLiveRoute
  '/admin/fit/messages': typeof AdminFitMessagesRoute
  '/admin/fit/nutrition': typeof AdminFitNutritionRoute
  '/admin/fit/portal': typeof AdminFitPortalRoute
  '/admin/fit/reviews': typeof AdminFitReviewsRoute
  '/admin/fit/scans': typeof AdminFitScansRoute
  '/admin/fit/videos': typeof AdminFitVideosRoute
  '/admin/fit/workouts': typeof AdminFitWorkoutsRouteWithChildren
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/portal/shop/$productId': typeof PortalShopProductIdRoute
  '/portal/shop/cart': typeof PortalShopCartRoute
  '/portal/shop/orders': typeof PortalShopOrdersRoute
  '/portal/visit/$id': typeof PortalVisitIdRoute
  '/admin/fit/': typeof AdminFitIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/portal/shop/': typeof PortalShopIndexRoute
  '/admin/fit/clients/$id': typeof AdminFitClientsIdRoute
  '/admin/fit/workouts/builder': typeof AdminFitWorkoutsBuilderRoute
  '/admin/fit/clients/': typeof AdminFitClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/arca'
    | '/ascend'
    | '/blog'
    | '/customers'
    | '/demo'
    | '/features'
    | '/login'
    | '/partners'
    | '/portal'
    | '/pricing'
    | '/security'
    | '/admin/acquisition'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/bookings-analytics'
    | '/admin/calendar'
    | '/admin/charts'
    | '/admin/coach-performance'
    | '/admin/dashboard'
    | '/admin/email-sms'
    | '/admin/fit'
    | '/admin/hipaa'
    | '/admin/intake'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/membership-health'
    | '/admin/memberships'
    | '/admin/messages'
    | '/admin/paid-channels'
    | '/admin/patients'
    | '/admin/phone-calls'
    | '/admin/photo-reviews'
    | '/admin/population'
    | '/admin/pos'
    | '/admin/product-revenue'
    | '/admin/products'
    | '/admin/protocols'
    | '/admin/rcm'
    | '/admin/referrals'
    | '/admin/reputation'
    | '/admin/results-gallery'
    | '/admin/scribe'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/telehealth'
    | '/admin/website'
    | '/blog/$slug'
    | '/compare/$competitor'
    | '/features/$slug'
    | '/portal/account'
    | '/portal/billing'
    | '/portal/labs'
    | '/portal/meds'
    | '/portal/messages'
    | '/portal/progress'
    | '/portal/visits'
    | '/admin/'
    | '/portal/'
    | '/admin/fit/billing'
    | '/admin/fit/business'
    | '/admin/fit/calendar'
    | '/admin/fit/challenges'
    | '/admin/fit/clients'
    | '/admin/fit/leads'
    | '/admin/fit/live'
    | '/admin/fit/messages'
    | '/admin/fit/nutrition'
    | '/admin/fit/portal'
    | '/admin/fit/reviews'
    | '/admin/fit/scans'
    | '/admin/fit/videos'
    | '/admin/fit/workouts'
    | '/admin/patients/$id'
    | '/portal/shop/$productId'
    | '/portal/shop/cart'
    | '/portal/shop/orders'
    | '/portal/visit/$id'
    | '/admin/fit/'
    | '/admin/patients/'
    | '/portal/shop/'
    | '/admin/fit/clients/$id'
    | '/admin/fit/workouts/builder'
    | '/admin/fit/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arca'
    | '/ascend'
    | '/blog'
    | '/customers'
    | '/demo'
    | '/features'
    | '/login'
    | '/partners'
    | '/pricing'
    | '/security'
    | '/admin/acquisition'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/bookings-analytics'
    | '/admin/calendar'
    | '/admin/charts'
    | '/admin/coach-performance'
    | '/admin/dashboard'
    | '/admin/email-sms'
    | '/admin/hipaa'
    | '/admin/intake'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/membership-health'
    | '/admin/memberships'
    | '/admin/messages'
    | '/admin/paid-channels'
    | '/admin/phone-calls'
    | '/admin/photo-reviews'
    | '/admin/population'
    | '/admin/pos'
    | '/admin/product-revenue'
    | '/admin/products'
    | '/admin/protocols'
    | '/admin/rcm'
    | '/admin/referrals'
    | '/admin/reputation'
    | '/admin/results-gallery'
    | '/admin/scribe'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/telehealth'
    | '/admin/website'
    | '/blog/$slug'
    | '/compare/$competitor'
    | '/features/$slug'
    | '/portal/account'
    | '/portal/billing'
    | '/portal/labs'
    | '/portal/meds'
    | '/portal/messages'
    | '/portal/progress'
    | '/portal/visits'
    | '/admin'
    | '/portal'
    | '/admin/fit/billing'
    | '/admin/fit/business'
    | '/admin/fit/calendar'
    | '/admin/fit/challenges'
    | '/admin/fit/leads'
    | '/admin/fit/live'
    | '/admin/fit/messages'
    | '/admin/fit/nutrition'
    | '/admin/fit/portal'
    | '/admin/fit/reviews'
    | '/admin/fit/scans'
    | '/admin/fit/videos'
    | '/admin/fit/workouts'
    | '/admin/patients/$id'
    | '/portal/shop/$productId'
    | '/portal/shop/cart'
    | '/portal/shop/orders'
    | '/portal/visit/$id'
    | '/admin/fit'
    | '/admin/patients'
    | '/portal/shop'
    | '/admin/fit/clients/$id'
    | '/admin/fit/workouts/builder'
    | '/admin/fit/clients'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/arca'
    | '/ascend'
    | '/blog'
    | '/customers'
    | '/demo'
    | '/features'
    | '/login'
    | '/partners'
    | '/portal'
    | '/pricing'
    | '/security'
    | '/admin/acquisition'
    | '/admin/analytics'
    | '/admin/billing'
    | '/admin/bookings-analytics'
    | '/admin/calendar'
    | '/admin/charts'
    | '/admin/coach-performance'
    | '/admin/dashboard'
    | '/admin/email-sms'
    | '/admin/fit'
    | '/admin/hipaa'
    | '/admin/intake'
    | '/admin/inventory'
    | '/admin/leads'
    | '/admin/locations'
    | '/admin/membership-health'
    | '/admin/memberships'
    | '/admin/messages'
    | '/admin/paid-channels'
    | '/admin/patients'
    | '/admin/phone-calls'
    | '/admin/photo-reviews'
    | '/admin/population'
    | '/admin/pos'
    | '/admin/product-revenue'
    | '/admin/products'
    | '/admin/protocols'
    | '/admin/rcm'
    | '/admin/referrals'
    | '/admin/reputation'
    | '/admin/results-gallery'
    | '/admin/scribe'
    | '/admin/settings'
    | '/admin/social'
    | '/admin/telehealth'
    | '/admin/website'
    | '/blog/$slug'
    | '/compare/$competitor'
    | '/features/$slug'
    | '/portal/account'
    | '/portal/billing'
    | '/portal/labs'
    | '/portal/meds'
    | '/portal/messages'
    | '/portal/progress'
    | '/portal/visits'
    | '/admin/'
    | '/portal/'
    | '/admin/fit/billing'
    | '/admin/fit/business'
    | '/admin/fit/calendar'
    | '/admin/fit/challenges'
    | '/admin/fit/clients'
    | '/admin/fit/leads'
    | '/admin/fit/live'
    | '/admin/fit/messages'
    | '/admin/fit/nutrition'
    | '/admin/fit/portal'
    | '/admin/fit/reviews'
    | '/admin/fit/scans'
    | '/admin/fit/videos'
    | '/admin/fit/workouts'
    | '/admin/patients/$id'
    | '/portal/shop/$productId'
    | '/portal/shop/cart'
    | '/portal/shop/orders'
    | '/portal/visit/$id'
    | '/admin/fit/'
    | '/admin/patients/'
    | '/portal/shop/'
    | '/admin/fit/clients/$id'
    | '/admin/fit/workouts/builder'
    | '/admin/fit/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArcaRoute: typeof ArcaRoute
  AscendRoute: typeof AscendRoute
  BlogRoute: typeof BlogRouteWithChildren
  CustomersRoute: typeof CustomersRoute
  DemoRoute: typeof DemoRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  SecurityRoute: typeof SecurityRoute
  CompareCompetitorRoute: typeof CompareCompetitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascend': {
      id: '/ascend'
      path: '/ascend'
      fullPath: '/ascend'
      preLoaderRoute: typeof AscendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arca': {
      id: '/arca'
      path: '/arca'
      fullPath: '/arca'
      preLoaderRoute: typeof ArcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/visits': {
      id: '/portal/visits'
      path: '/visits'
      fullPath: '/portal/visits'
      preLoaderRoute: typeof PortalVisitsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/progress': {
      id: '/portal/progress'
      path: '/progress'
      fullPath: '/portal/progress'
      preLoaderRoute: typeof PortalProgressRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/meds': {
      id: '/portal/meds'
      path: '/meds'
      fullPath: '/portal/meds'
      preLoaderRoute: typeof PortalMedsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/labs': {
      id: '/portal/labs'
      path: '/labs'
      fullPath: '/portal/labs'
      preLoaderRoute: typeof PortalLabsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/compare/$competitor': {
      id: '/compare/$competitor'
      path: '/compare/$competitor'
      fullPath: '/compare/$competitor'
      preLoaderRoute: typeof CompareCompetitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/telehealth': {
      id: '/admin/telehealth'
      path: '/telehealth'
      fullPath: '/admin/telehealth'
      preLoaderRoute: typeof AdminTelehealthRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/social': {
      id: '/admin/social'
      path: '/social'
      fullPath: '/admin/social'
      preLoaderRoute: typeof AdminSocialRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scribe': {
      id: '/admin/scribe'
      path: '/scribe'
      fullPath: '/admin/scribe'
      preLoaderRoute: typeof AdminScribeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/results-gallery': {
      id: '/admin/results-gallery'
      path: '/results-gallery'
      fullPath: '/admin/results-gallery'
      preLoaderRoute: typeof AdminResultsGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reputation': {
      id: '/admin/reputation'
      path: '/reputation'
      fullPath: '/admin/reputation'
      preLoaderRoute: typeof AdminReputationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rcm': {
      id: '/admin/rcm'
      path: '/rcm'
      fullPath: '/admin/rcm'
      preLoaderRoute: typeof AdminRcmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/protocols': {
      id: '/admin/protocols'
      path: '/protocols'
      fullPath: '/admin/protocols'
      preLoaderRoute: typeof AdminProtocolsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/product-revenue': {
      id: '/admin/product-revenue'
      path: '/product-revenue'
      fullPath: '/admin/product-revenue'
      preLoaderRoute: typeof AdminProductRevenueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/population': {
      id: '/admin/population'
      path: '/population'
      fullPath: '/admin/population'
      preLoaderRoute: typeof AdminPopulationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/photo-reviews': {
      id: '/admin/photo-reviews'
      path: '/photo-reviews'
      fullPath: '/admin/photo-reviews'
      preLoaderRoute: typeof AdminPhotoReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/phone-calls': {
      id: '/admin/phone-calls'
      path: '/phone-calls'
      fullPath: '/admin/phone-calls'
      preLoaderRoute: typeof AdminPhoneCallsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/paid-channels': {
      id: '/admin/paid-channels'
      path: '/paid-channels'
      fullPath: '/admin/paid-channels'
      preLoaderRoute: typeof AdminPaidChannelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/membership-health': {
      id: '/admin/membership-health'
      path: '/membership-health'
      fullPath: '/admin/membership-health'
      preLoaderRoute: typeof AdminMembershipHealthRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intake': {
      id: '/admin/intake'
      path: '/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AdminIntakeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/hipaa': {
      id: '/admin/hipaa'
      path: '/hipaa'
      fullPath: '/admin/hipaa'
      preLoaderRoute: typeof AdminHipaaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fit': {
      id: '/admin/fit'
      path: '/fit'
      fullPath: '/admin/fit'
      preLoaderRoute: typeof AdminFitRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email-sms': {
      id: '/admin/email-sms'
      path: '/email-sms'
      fullPath: '/admin/email-sms'
      preLoaderRoute: typeof AdminEmailSmsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coach-performance': {
      id: '/admin/coach-performance'
      path: '/coach-performance'
      fullPath: '/admin/coach-performance'
      preLoaderRoute: typeof AdminCoachPerformanceRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/charts': {
      id: '/admin/charts'
      path: '/charts'
      fullPath: '/admin/charts'
      preLoaderRoute: typeof AdminChartsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings-analytics': {
      id: '/admin/bookings-analytics'
      path: '/bookings-analytics'
      fullPath: '/admin/bookings-analytics'
      preLoaderRoute: typeof AdminBookingsAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/acquisition': {
      id: '/admin/acquisition'
      path: '/acquisition'
      fullPath: '/admin/acquisition'
      preLoaderRoute: typeof AdminAcquisitionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/shop/': {
      id: '/portal/shop/'
      path: '/shop'
      fullPath: '/portal/shop/'
      preLoaderRoute: typeof PortalShopIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/fit/': {
      id: '/admin/fit/'
      path: '/'
      fullPath: '/admin/fit/'
      preLoaderRoute: typeof AdminFitIndexRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/portal/visit/$id': {
      id: '/portal/visit/$id'
      path: '/visit/$id'
      fullPath: '/portal/visit/$id'
      preLoaderRoute: typeof PortalVisitIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/shop/orders': {
      id: '/portal/shop/orders'
      path: '/shop/orders'
      fullPath: '/portal/shop/orders'
      preLoaderRoute: typeof PortalShopOrdersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/shop/cart': {
      id: '/portal/shop/cart'
      path: '/shop/cart'
      fullPath: '/portal/shop/cart'
      preLoaderRoute: typeof PortalShopCartRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/shop/$productId': {
      id: '/portal/shop/$productId'
      path: '/shop/$productId'
      fullPath: '/portal/shop/$productId'
      preLoaderRoute: typeof PortalShopProductIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/fit/workouts': {
      id: '/admin/fit/workouts'
      path: '/workouts'
      fullPath: '/admin/fit/workouts'
      preLoaderRoute: typeof AdminFitWorkoutsRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/videos': {
      id: '/admin/fit/videos'
      path: '/videos'
      fullPath: '/admin/fit/videos'
      preLoaderRoute: typeof AdminFitVideosRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/scans': {
      id: '/admin/fit/scans'
      path: '/scans'
      fullPath: '/admin/fit/scans'
      preLoaderRoute: typeof AdminFitScansRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/reviews': {
      id: '/admin/fit/reviews'
      path: '/reviews'
      fullPath: '/admin/fit/reviews'
      preLoaderRoute: typeof AdminFitReviewsRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/portal': {
      id: '/admin/fit/portal'
      path: '/portal'
      fullPath: '/admin/fit/portal'
      preLoaderRoute: typeof AdminFitPortalRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/nutrition': {
      id: '/admin/fit/nutrition'
      path: '/nutrition'
      fullPath: '/admin/fit/nutrition'
      preLoaderRoute: typeof AdminFitNutritionRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/messages': {
      id: '/admin/fit/messages'
      path: '/messages'
      fullPath: '/admin/fit/messages'
      preLoaderRoute: typeof AdminFitMessagesRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/live': {
      id: '/admin/fit/live'
      path: '/live'
      fullPath: '/admin/fit/live'
      preLoaderRoute: typeof AdminFitLiveRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/leads': {
      id: '/admin/fit/leads'
      path: '/leads'
      fullPath: '/admin/fit/leads'
      preLoaderRoute: typeof AdminFitLeadsRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/clients': {
      id: '/admin/fit/clients'
      path: '/clients'
      fullPath: '/admin/fit/clients'
      preLoaderRoute: typeof AdminFitClientsRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/challenges': {
      id: '/admin/fit/challenges'
      path: '/challenges'
      fullPath: '/admin/fit/challenges'
      preLoaderRoute: typeof AdminFitChallengesRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/calendar': {
      id: '/admin/fit/calendar'
      path: '/calendar'
      fullPath: '/admin/fit/calendar'
      preLoaderRoute: typeof AdminFitCalendarRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/business': {
      id: '/admin/fit/business'
      path: '/business'
      fullPath: '/admin/fit/business'
      preLoaderRoute: typeof AdminFitBusinessRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/billing': {
      id: '/admin/fit/billing'
      path: '/billing'
      fullPath: '/admin/fit/billing'
      preLoaderRoute: typeof AdminFitBillingRouteImport
      parentRoute: typeof AdminFitRoute
    }
    '/admin/fit/clients/': {
      id: '/admin/fit/clients/'
      path: '/'
      fullPath: '/admin/fit/clients/'
      preLoaderRoute: typeof AdminFitClientsIndexRouteImport
      parentRoute: typeof AdminFitClientsRoute
    }
    '/admin/fit/workouts/builder': {
      id: '/admin/fit/workouts/builder'
      path: '/builder'
      fullPath: '/admin/fit/workouts/builder'
      preLoaderRoute: typeof AdminFitWorkoutsBuilderRouteImport
      parentRoute: typeof AdminFitWorkoutsRoute
    }
    '/admin/fit/clients/$id': {
      id: '/admin/fit/clients/$id'
      path: '/$id'
      fullPath: '/admin/fit/clients/$id'
      preLoaderRoute: typeof AdminFitClientsIdRouteImport
      parentRoute: typeof AdminFitClientsRoute
    }
  }
}

interface AdminFitClientsRouteChildren {
  AdminFitClientsIdRoute: typeof AdminFitClientsIdRoute
  AdminFitClientsIndexRoute: typeof AdminFitClientsIndexRoute
}

const AdminFitClientsRouteChildren: AdminFitClientsRouteChildren = {
  AdminFitClientsIdRoute: AdminFitClientsIdRoute,
  AdminFitClientsIndexRoute: AdminFitClientsIndexRoute,
}

const AdminFitClientsRouteWithChildren = AdminFitClientsRoute._addFileChildren(
  AdminFitClientsRouteChildren,
)

interface AdminFitWorkoutsRouteChildren {
  AdminFitWorkoutsBuilderRoute: typeof AdminFitWorkoutsBuilderRoute
}

const AdminFitWorkoutsRouteChildren: AdminFitWorkoutsRouteChildren = {
  AdminFitWorkoutsBuilderRoute: AdminFitWorkoutsBuilderRoute,
}

const AdminFitWorkoutsRouteWithChildren =
  AdminFitWorkoutsRoute._addFileChildren(AdminFitWorkoutsRouteChildren)

interface AdminFitRouteChildren {
  AdminFitBillingRoute: typeof AdminFitBillingRoute
  AdminFitBusinessRoute: typeof AdminFitBusinessRoute
  AdminFitCalendarRoute: typeof AdminFitCalendarRoute
  AdminFitChallengesRoute: typeof AdminFitChallengesRoute
  AdminFitClientsRoute: typeof AdminFitClientsRouteWithChildren
  AdminFitLeadsRoute: typeof AdminFitLeadsRoute
  AdminFitLiveRoute: typeof AdminFitLiveRoute
  AdminFitMessagesRoute: typeof AdminFitMessagesRoute
  AdminFitNutritionRoute: typeof AdminFitNutritionRoute
  AdminFitPortalRoute: typeof AdminFitPortalRoute
  AdminFitReviewsRoute: typeof AdminFitReviewsRoute
  AdminFitScansRoute: typeof AdminFitScansRoute
  AdminFitVideosRoute: typeof AdminFitVideosRoute
  AdminFitWorkoutsRoute: typeof AdminFitWorkoutsRouteWithChildren
  AdminFitIndexRoute: typeof AdminFitIndexRoute
}

const AdminFitRouteChildren: AdminFitRouteChildren = {
  AdminFitBillingRoute: AdminFitBillingRoute,
  AdminFitBusinessRoute: AdminFitBusinessRoute,
  AdminFitCalendarRoute: AdminFitCalendarRoute,
  AdminFitChallengesRoute: AdminFitChallengesRoute,
  AdminFitClientsRoute: AdminFitClientsRouteWithChildren,
  AdminFitLeadsRoute: AdminFitLeadsRoute,
  AdminFitLiveRoute: AdminFitLiveRoute,
  AdminFitMessagesRoute: AdminFitMessagesRoute,
  AdminFitNutritionRoute: AdminFitNutritionRoute,
  AdminFitPortalRoute: AdminFitPortalRoute,
  AdminFitReviewsRoute: AdminFitReviewsRoute,
  AdminFitScansRoute: AdminFitScansRoute,
  AdminFitVideosRoute: AdminFitVideosRoute,
  AdminFitWorkoutsRoute: AdminFitWorkoutsRouteWithChildren,
  AdminFitIndexRoute: AdminFitIndexRoute,
}

const AdminFitRouteWithChildren = AdminFitRoute._addFileChildren(
  AdminFitRouteChildren,
)

interface AdminPatientsRouteChildren {
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsIdRoute: AdminPatientsIdRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAcquisitionRoute: typeof AdminAcquisitionRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminBookingsAnalyticsRoute: typeof AdminBookingsAnalyticsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminChartsRoute: typeof AdminChartsRoute
  AdminCoachPerformanceRoute: typeof AdminCoachPerformanceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmailSmsRoute: typeof AdminEmailSmsRoute
  AdminFitRoute: typeof AdminFitRouteWithChildren
  AdminHipaaRoute: typeof AdminHipaaRoute
  AdminIntakeRoute: typeof AdminIntakeRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminMembershipHealthRoute: typeof AdminMembershipHealthRoute
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPaidChannelsRoute: typeof AdminPaidChannelsRoute
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminPhoneCallsRoute: typeof AdminPhoneCallsRoute
  AdminPhotoReviewsRoute: typeof AdminPhotoReviewsRoute
  AdminPopulationRoute: typeof AdminPopulationRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminProductRevenueRoute: typeof AdminProductRevenueRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProtocolsRoute: typeof AdminProtocolsRoute
  AdminRcmRoute: typeof AdminRcmRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminReputationRoute: typeof AdminReputationRoute
  AdminResultsGalleryRoute: typeof AdminResultsGalleryRoute
  AdminScribeRoute: typeof AdminScribeRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSocialRoute: typeof AdminSocialRoute
  AdminTelehealthRoute: typeof AdminTelehealthRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAcquisitionRoute: AdminAcquisitionRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminBookingsAnalyticsRoute: AdminBookingsAnalyticsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminChartsRoute: AdminChartsRoute,
  AdminCoachPerformanceRoute: AdminCoachPerformanceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmailSmsRoute: AdminEmailSmsRoute,
  AdminFitRoute: AdminFitRouteWithChildren,
  AdminHipaaRoute: AdminHipaaRoute,
  AdminIntakeRoute: AdminIntakeRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminMembershipHealthRoute: AdminMembershipHealthRoute,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPaidChannelsRoute: AdminPaidChannelsRoute,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminPhoneCallsRoute: AdminPhoneCallsRoute,
  AdminPhotoReviewsRoute: AdminPhotoReviewsRoute,
  AdminPopulationRoute: AdminPopulationRoute,
  AdminPosRoute: AdminPosRoute,
  AdminProductRevenueRoute: AdminProductRevenueRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProtocolsRoute: AdminProtocolsRoute,
  AdminRcmRoute: AdminRcmRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminReputationRoute: AdminReputationRoute,
  AdminResultsGalleryRoute: AdminResultsGalleryRoute,
  AdminScribeRoute: AdminScribeRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSocialRoute: AdminSocialRoute,
  AdminTelehealthRoute: AdminTelehealthRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface FeaturesRouteChildren {
  FeaturesSlugRoute: typeof FeaturesSlugRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesSlugRoute: FeaturesSlugRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalBillingRoute: typeof PortalBillingRoute
  PortalLabsRoute: typeof PortalLabsRoute
  PortalMedsRoute: typeof PortalMedsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProgressRoute: typeof PortalProgressRoute
  PortalVisitsRoute: typeof PortalVisitsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalShopProductIdRoute: typeof PortalShopProductIdRoute
  PortalShopCartRoute: typeof PortalShopCartRoute
  PortalShopOrdersRoute: typeof PortalShopOrdersRoute
  PortalVisitIdRoute: typeof PortalVisitIdRoute
  PortalShopIndexRoute: typeof PortalShopIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalBillingRoute: PortalBillingRoute,
  PortalLabsRoute: PortalLabsRoute,
  PortalMedsRoute: PortalMedsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProgressRoute: PortalProgressRoute,
  PortalVisitsRoute: PortalVisitsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalShopProductIdRoute: PortalShopProductIdRoute,
  PortalShopCartRoute: PortalShopCartRoute,
  PortalShopOrdersRoute: PortalShopOrdersRoute,
  PortalVisitIdRoute: PortalVisitIdRoute,
  PortalShopIndexRoute: PortalShopIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArcaRoute: ArcaRoute,
  AscendRoute: AscendRoute,
  BlogRoute: BlogRouteWithChildren,
  CustomersRoute: CustomersRoute,
  DemoRoute: DemoRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  SecurityRoute: SecurityRoute,
  CompareCompetitorRoute: CompareCompetitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
